# permissions for end users to view bpfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: bpf-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ebpf-operator
    app.kubernetes.io/part-of: ebpf-operator
    app.kubernetes.io/managed-by: kustomize
  name: bpf-viewer-role
rules:
- apiGroups:
  - bpf.cloud
  resources:
  - bpfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpf.cloud
  resources:
  - bpfs/status
  verbs:
  - get
